version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: biosensor
      POSTGRES_USER: biosensor_user
      POSTGRES_PASSWORD: biosensor_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biosensor_user -d biosensor"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://biosensor_user:biosensor_pass@db:5432/biosensor
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["/bin/uv", "run", "server"]

volumes:
  postgres_data: